import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-white h-screen flex flex-col overflow-y-hidden`}>
        <div className="w-full bg-gray-800 p-4 flex justify-between items-center mb-2">
          <div className="text-lg font-bold">My App</div>
          <nav className="flex gap-4">
            <a href="/home" className="text-gray-300 hover:text-white">Home</a>
            <a href="/login" className="text-gray-300 hover:text-white">Login</a>
          </nav>
        </div>
        <div className="flex flex-1 overflow-y-auto w-100vw justify-center items-center">
          {children}
        </div>
      </body>
    </html>
  );
}